config/routes.rb
Map::Application.routes.draw do

  resources :games do
    resources :player_states
    resources :voting_profiles

    post "roll"
    get "reset", :on => :member
    get "players"
  end

  resources :elections do
    member do 
      get :update_vote_table
    end
    resources :events
    resources :candidates
  end

  resources :events do
  end

  match 'event/outcome' => 'events#outcome', :via => :post
  match 'event/activate' => 'events#activate'

  match '/events/:event_id/:response' => 'events#outcome', :as=> :outcome, :via => :get

  get "maps/show"

root :to => 'games#new'

end

app/models/election.rb
# == Schema Information
#
# Table name: elections
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  game_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  date       :date
#



class Election < ActiveRecord::Base
  validates  :name, presence: true
  #, uniqueness: { case_sensitive: false }
  attr_accessible :game_id, :name, :date
  has_many :events
  has_many :candidates
  belongs_to :game

  attr_reader :start_date
  #
  # Start date of campaign cycle is 1st of months, two months before month
  # of election. 
  #
  def start_date
    puts "@@@@@@ #{date.year} #{date.month}"
  	@start_date ||= Date.new(date.year, date.month-2, 1)
  end
  #
  # Convert a value represent 'days into campaign' into
  # a date
  #
  def campaign_date(to)
    start_date + to.days
  end

  #
  # Number of days in campaign
  #
  def campaign_length
    (self.date - self.start_date).to_i
  end

  #
  # Return event for player on given date
  def event_for(candidate, date)
    results = events.where(:date => date..(date + 1.day))
    results.where(:candidate_id =>  candidate.id)[0] || results.where(:candidate_id => Candidate.find_by_name("candidate"))[0]
  end

  def active_candidates
    candidates.select { |c| c.name != "candidate" }
  end

  def candidate_for(name) 
    candidates.where("name = ?", name).first
  end

end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController

  respond_to :js, :html
  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elections }
    end
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
    @election = Election.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/new
  # GET /elections/new.json
  def new
    @election = Election.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @election }
    end
  end

  # GET /elections/1/edit
  def edit
    @election = Election.find(params[:id])
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(params[:election])

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render json: @election, status: :created, location: @election }
      else
        format.html { render action: "new" }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elections/1
  # PUT /elections/1.json
  def update
    @election = Election.find(params[:id])

    respond_to do |format|
      if @election.update_attributes(params[:election])
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election = Election.find(params[:id])
    @election.destroy

    respond_to do |format|
      format.html { redirect_to elections_url }
      format.json { head :no_content }
    end
  end


  def update_vote_table
    @election = Election.find(params[:id])
    respond_with(@election)
  end
end

app/helpers/elections_helper.rb
module ElectionsHelper

	def election_year(election)
        election.date.year
    end

    def campaign_start_day(election)
    	1
    end

    def campaign_start_month(election)
    	election.date.month-2
    end

    def election_cycle
    	3
    end

    def vote_table_id(election)
        "vt_#{election.id}"
    end

    def vote_table(candidates)
        out =  %Q[<table class="table table-bordered" >]
        out += %Q[<thead><td>Candidate</td><td>Popular Votes</td><td>Electoral Votes</td></tr></thead>]
        candidates.each do |c|
            out += %Q[<tr><td width="35%">#{c.name}</td><td>#{c.voting_profiles.collect { |x| x.votes }.reduce(:+)}</td>\
                        <td>#{c.electoral_votes}</td>\
                        </tr>]
        end
        out += "</table>"
        out.html_safe
    end
end

app/views/elections/_form.html.erb
<%= form_for(@election) do |f| %>
  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% @election.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<h1>Editing election</h1>

<%= render 'form' %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

app/views/elections/index.html.erb
<h1>Listing elections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Game</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elections.each do |election| %>
  <tr>
    <td><%= election.name %></td>
    <td><%= election.game_id %></td>
    <td><%= link_to 'Show', election %></td>
    <td><%= link_to 'Edit', edit_election_path(election) %></td>
    <td><%= link_to 'Destroy', election, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Election', new_election_path %>

app/views/elections/new.html.erb
<h1>New election</h1>

<%= render 'form' %>

<%= link_to 'Back', elections_path %>

app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @election.name %>
</p>

<p>
  <b>Game:</b>
  <%= @election.game_id %>
</p>


<%= link_to 'Edit', edit_election_path(@election) %> |
<%= link_to 'Back', elections_path %>

app/views/elections/update_vote_table.js.erb
$('#game-over-modal-body').html('<%= vote_table(@election.active_candidates) %>')