config/routes.rb
Map::Application.routes.draw do

  resources :games do
    resources :player_states
    resources :voting_profiles

    post "roll"
    get "reset", :on => :member
    get "players"
  end

  resources :elections do
    member do 
      get :update_vote_table
    end
    resources :events
    resources :candidates
  end

  resources :events do
  end

  match 'event/outcome' => 'events#outcome', :via => :post
  match 'event/activate' => 'events#activate'

  match '/events/:event_id/:response' => 'events#outcome', :as=> :outcome, :via => :get

  get "maps/show"

root :to => 'games#new'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :integer         not null, primary key
#  election_id  :integer
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  config_file  :string(255)
#  start_date   :date
#  candidate_id :integer
#  current_turn :integer         default(0)
#  max_position :integer
#

class Game < ActiveRecord::Base
  attr_accessible :config_file, :start_date
  belongs_to :election
  has_many   :player_states, autosave: :true
  belongs_to :player_in_turn, class_name: "Candidate", foreign_key: :candidate_id
  
  def advance(player, steps)
    s = state_for(player)
    s.location = [self.max_position, s.location + steps].min
    s.save
  end

  def location(player)
  	state_for(player).location
  end

  def state_for(player) 
  	player_states.select { |s| s.player_id == player.id }[0]
  end

  def next_turn
    self.current_turn = (self.current_turn + 1) % player_states.size
    self.player_in_turn = self.election.active_candidates[self.current_turn]
  end

  def setup(an_election = nil)
    election = self.election ||= an_election
    player_states.delete_all
    election.active_candidates.collect { |c| 
      self.player_states.build(player_id: c.id, type_of: c.class.to_s)
    } 
    self.current_turn = 0
    self.max_position = election.campaign_length
    self.player_in_turn = election.active_candidates[0]
    self.election = election
    self.save
  end

  def over?
     player_states.select { |p| p.location == self.max_position }.size == player_states.size
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper
  caches_action :show
  respond_to :json, :html
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @election = @game.election
    @game.setup(@election)
    
    respond_with(@game)
  end

  # GET /games/new
  # GET /games/new.json
  def new
  
    ActiveRecord::Base.connection.reconnect!

    @game = Game.new
    
    d = Dir.new("./lib/config/elections")
    @config_dirs =  d.each.select { |f| File.directory?(File.join(d.path,f)) && f =~ /\w+/ }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    
    config = Configurator.new(@game.config_file, @game.start_date)
    @election = config.persist
    @game.setup(@election)
 

    respond_to do |format|
      if @game.save
        @election.game = @game
        @election.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def roll
    game = Game.find(params[:game_id])
    die = params[:die]
    roll_total = die.collect { |v| v.to_i }.sum
    response = do_move(game, roll_total)

    respond_to do |format|
      format.json { render json: response }
      format.html
    end

  end

  def reset
    expire_action :action => :show
    @game = Game.find(params[:id])
    logger.debug("**********   #{@game}  #{@game.inspect}")
    @game.setup
 
    redirect_to game_path(@game)
  end

  def do_move(game, roll_total) 
    mover = game.player_in_turn

    from  = game.location(mover)
   
    game.advance(mover,roll_total)
    to = game.location(mover)

    landing_date = game.election.campaign_date(to)
    landing_date_event = game.election.event_for(mover, landing_date)
    game.next_turn
    game.save

    move_helper(game.player_in_turn.name, game.over?,
                     [{ 
                        :player=> mover.name,
                        :player_id =>  mover.id,
                        :token => mover.image,
                        :to => to,
                        :from => from,
                        :event=> (landing_date_event.id rescue -1) }])
  end
end

app/helpers/games_helper.rb
module GamesHelper

	def json_electoral_votes(game)
	    votes = {}
	    State.all.each { |s|   votes[s.state_tag] = s.electoral_votes.to_s }
	    votes.to_json.html_safe
	end
	def json_voting_profiles(game)
		profiles = {}
		VotingProfile.where("election_id = ?", game.election_id).each do  |vp| 
			profiles[vp.state.state_tag] = [] if profiles[vp.state.state_tag].nil?
			profiles[vp.state.state_tag] << { :name => vp.candidate.name, :votes => vp.votes }
		end
		profiles.to_json.html_safe
	end
# TODO de-couple from specific candidates
	def json_percent_differential(game)
		percent_diff_map = {}
		gore = Candidate.find_by_name("Gore")
		bush = Candidate.find_by_name("Bush")
		percent_diff_map['red_states'] = State.margin_map(bush)
		percent_diff_map['blue_states'] = State.margin_map(gore)

		percent_diff_map.to_json.html_safe
	end

	def move_helper(tomove_name, game_over_flag, moves) 
		{  :player_in_turn => tomove_name, 
           :moves => moves,
           :game_over => game_over_flag
        }
    end

end

app/views/games/_form.html.erb
<div class='row' >
  <div class='span8 offset2' >
  <% require 'date' %>
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= "Error : #{msg}" %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Election Configuration Files" %><br />
    <%= f.select :config_file, @config_dirs, {}, :class=>'config_select' %>
  </div>
  <div class="field">
    <%= f.label "Date of Election" %><br />
    <%= f.date_select :start_date, 
            { :default => {:year => 2008, :month => 11, :day => 4},
              :use_short_month=>true },
            :class=>'date_select' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>


</div>
<% if Rails.env.development? %>
<div class="debug-panel">
  <%= debug (@game.inspect) %>
  <%= debug (Game.all.inspect) %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Election</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.election_id %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>Electoral Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="center hero-unit" >

<div class='span12' >
  <div class="row">
    <div class='span3' id="jCalTarget" ></div>
    <div  class='span9' >
      <div class='row'>
        <div id="us-map" class='span8' style="width:600px;height: 400px"></div>
        <div class='span1' style="position:relative; top:330px;left:-250px">
          <i class='icon-retweet' onclick="recolor(this);" ></i>
          <span style="font-size:8px"  id='popular_vote_scheme'>Color by Popular Vote</span>
          <span style="font-size:8px"  id='electoral_vote_scheme' >Color by Electoral Vote</span>
        </div>
      </div>
      
      <div class='row'>
        <div id=<%= vote_table_id(@election) %> class='span6' >
          <%= vote_table(@election.active_candidates) %>
        </div>
      </div>
      <div class='row'>
         <div class="span2">
           <%= roll_tag(@game) %>
         </div>
         <br/>
         <div class='span3'>
            <%= button_tag( 'New Game', 
                 :onclick=> 'reset_button(this);',
                 :class=> 'btn btn-primary') %>
         </div>
      </div>
    </div>
  </div>
</div>

<div id='game-over-modal' class='modal hide fade'
  role="dialog" aria-labelledby="results-modal-label" aria-hidden="true">
  <div class='modal-header' >
    <button type="button" 
            class="close" 
            data-dismiss="modal" 
            aria-hidden="true">×</button>
    <h3 id='results-modal-label'>Election Results</h3>
  </div>
  <div id='game-over-modal-body' class='modal-body' >
  </div>
</div>



  <script>
 $('#game-over-modal').on('show', function () {
      $.get('<%= update_vote_table_election_path(@election) %>', {}, "js"); 
  });

   function recolor_handler(data){
      var mapObject = $('#us-map').vectorMap('get', 'mapObject');
      $(colorScheme).show();
      if (colorScheme == '#electoral_vote_scheme' ) {
       // toggle to popular
      red_states = jvm.values.apply({}, jvm.values(data.percent_differential.red_states));
      blue_states = jvm.values.apply({}, jvm.values(data.percent_differential.blue_states));

       
  
        mapObject.series.regions[0].setScale(['#f4e6e6', '#f72a2a']);
        mapObject.series.regions[0].setValues(data.percent_differential.red_states);
         mapObject.series.regions[1].setScale(
          ['#DEEBF7', '#08519C']);
        mapObject.series.regions[1].setValues(data.percent_differential.blue_states);
       
        colorScheme = '#popular_vote_scheme';
      } else {
         mapObject.series.regions[0].setScale(['#DEEBF7', '#08519C']);
        mapObject.series.regions[0].setValues(data.electoral_votes);
        mapObject.series.regions[1].setValues([]);
        colorScheme = '#electoral_vote_scheme';
      }
      $(colorScheme).hide();


    };

   var colorScheme = '#electoral_vote_scheme';
  function recolor(element) { 

    $.getJSON(<%= "\'#{game_path(@game)}\'" %>, recolor_handler);

  };

  function date_to_tag(date) {
    
    return "#c" +$('.jCalMo').length + "d_" 
                    + (date.getMonth()+1) + "_" 
                    + date.getDate() + "_"
                    +date.getFullYear();
  };

$('#jCalTarget').jCal({
	day:			new Date(<%= election_year(@election) %>, 
                 <%= campaign_start_month(@election)-1 %>, 
                 <%= campaign_start_day(@election) %>),
	days:			1,
	showMonths:		<%= election_cycle %>,
	monthSelect:		false,
  scrollable:          false, 
	callback:		function (day, days) {
		// This is selected element, that is, a 'day' div 
			elem =$(date_to_tag(day));
		}
	});


  function initialize_game(data){
  
    var year = 2008;
    $('#electoral_vote_scheme').hide();
    // Remove any existing player
    $("div[class*='player']").remove();
    handle_move(data.moves);

    statesValues = jvm.values.apply({}, jvm.values(data.electoral_votes));

    // Remove div for map
    $('.jvectormap-container').remove();
    $('#us-map').vectorMap({
      map: 'us_aea_en',
      backgroundColor: '#707070',
      series: {
       
        regions: [{
          scale: ['#DEEBF7', '#08519C'],
          attribute: 'fill',
          values: data.electoral_votes,
          min: jvm.min(statesValues),
          max: jvm.max(statesValues)
        },
        {
          scale: ['#DEEBF7', '#08519C'],
          attribute: 'fill',
          values: [],
          min: jvm.min(statesValues),
          max: jvm.max(statesValues)
        }]
      },
      onMarkerLabelShow: function(event, label, index){
        label.html(
          ''+data.metro.names[index]+'<br/>'+
          'Population: '+data.metro.population[year][index]+'<br/>'+
          'Unemployment rate: '+data.metro.unemployment[year][index]
        );
      },
      onRegionLabelShow: function(event, label, state_code){
        vps = data.voting_profiles[state_code];
        str = "";

       for (i = 0; i  < vps.length; i++) {
         str += vps[i].name + ": " + vps[i].votes + "<br/>";
       }
       
        label.html(
          ''+label.html()+'<br/>'+
          'Electoral Votes: '+data.electoral_votes[state_code] + "<br/>" 
           + str
        );
      }
    });

    var mapObject = $('#us-map').vectorMap('get', 'mapObject');

    $(function() {
      $.get(<%= "\'#{election_events_path(@election)}\'" %>, {}, "js" );
    });


  }

  $(function(){
    $.getJSON(<%= "\'#{game_path(@game)}\'" %>, 
       function(data) { initialize_game(data) } );
  });

function handle_move(data) {
  date_str = <%= "\'#{@election.start_date.to_s}\';" %>


  date_parts = date_str.split("-");
  start_date = new Date(date_parts[0], date_parts[1]-1, date_parts[2]);

  moves = data.moves;
              
  for (var i = 0; i < moves.length; i++) {
    player = moves[i].player;
    player_id = moves[i].player_id;
    token = moves[i].token;
    
    from = moves[i].from;
    if (from != undefined) {

      from_date = new Date(date_parts[0], date_parts[1]-1, parseInt(date_parts[2]) + parseInt(from) );
      rm_day_id = date_to_tag(from_date);
    
      rm_selector = rm_day_id +" >  div[title='" + player + "']";
      $(rm_selector).remove(); 
      pieces = $(rm_day_id + " div");
      for (var k = 0; k < pieces.length; k++) {
        pieces[k].className = "player" + k
      }

    }
    to = moves[i].to;
    to_date = new Date(date_parts[0], date_parts[1]-1, parseInt(date_parts[2]) + parseInt(to) );
  
          
    to_day_id = date_to_tag(to_date);
    
    style_id = $(to_day_id + " div").length;
    $(to_day_id).html(
      $(to_day_id).html()+"<div title=" 
                 + "'" + player + "'"
                 + " class='player" + style_id + "'>" 
                 +"<i class='"
                 +token
                 +"'></i></div>");
    //$(to_day_id).popover('show'); 
    // If move landing has an associated event,
    // request popover for it.
    if (moves[i].event > 0) {
      $.get(<%= "\'#{event_activate_path}\'" %>, 
              { 'candidate_id' : player_id, 'event_id' : moves[i].event}, 
              "js");
            
    }

  }
  if (data.game_over == true) {
    $('#game-over-modal').modal('show');
  }
}

// re-initialize game
function reset_button(e) {
    $.getJSON(<%= "\'#{reset_game_path(@game)}\'" %>, 
        function(data) { initialize_game(data); });
};
</script>

app/views/games/show.json.erb
{
	"moves" : <%= move_helper(@game.player_in_turn.name, false,
		@game.election.active_candidates.each.collect do |c|
			{ :player=> c.name, 
			  :player_id => c.id,
                    :token => c.image,
                    :to => 0,
                    :event=> -1
			}
		end ).to_json.html_safe
	    %>,
"electoral_votes": <%= json_electoral_votes(@game) %>,
"percent_differential" : <%= json_percent_differential(@game) %>,
"voting_profiles": <%= json_voting_profiles(@game) %>,
"states":
{"2005":
 {"US-AL":7.2,"US-AK":8.6,"US-AZ":6.3,"US-AR":6.9,"US-CA":7.2,"US-CO":6.2,"US-CT":6.3,"US-DE":5.6,"US-DC":9.1,"US-FL":6.3,"US-GA":7.4,"US-HI":4.4,"US-ID":5.8,"US-IL":7.9,"US-IN":6.9,"US-IA":5.1,"US-KS":5.5,"US-KY":7.5,"US-LA":9.0,"US-ME":5.7,"US-MD":5.7,"US-MA":6.4,"US-MI":8.9},
 "2006":
 {"US-MN":5.2,"US-MS":8.9,"US-MO":6.3,"US-MT":4.8,"US-NE":4.8,"US-NV":5.2,"US-NH":4.5,"US-NJ":6.3,"US-NM":6.4,"US-NY":6.5,"US-NC":6.6,"US-ND":3.3,"US-OH":7.1,"US-OK":6.0,"US-OR":6.3,"US-PA":6.2,"US-RI":5.9,"US-SC":7.4,"US-SD":4.3,"US-TN":7.4,"US-TX":7.0,"US-UT":4.4,"US-VT":4.8,"US-VA":4.7,"US-WA":6.4,"US-WV":6.8,"US-WI":5.5,"US-WY":3.5},
 "2007":
 {"US-AL":6.7,"US-AK":8.8,"US-AZ":5.8,"US-AR":7.2,"US-CA":6.6,"US-CO":5.5,"US-CT":6.0,"US-DE":5.6,"US-DC":8.1,"US-FL":6.2,"US-GA":7.0,"US-HI":4.5,"US-ID":5.1,"US-IL":7.2,"US-IN":6.6,"US-IA":4.8,"US-KS":5.1,"US-KY":6.6,"US-LA":6.4,"US-ME":6.0,"US-MD":5.5,"US-MA":6.1,"US-MI":9.6,"US-MN":5.4,"US-MS":9.3,"US-MO":6.3,"US-MT":5.2,"US-NE":4.6,"US-NV":5.6,"US-NH":5.1,"US-NJ":5.9,"US-NM":5.6,"US-NY":6.2,"US-NC":6.9,"US-ND":3.5,"US-OH":7.2,"US-OK":5.4,"US-OR":6.5,"US-PA":5.9,"US-RI":6.3,"US-SC":6.9,"US-SD":4.1,"US-TN":6.9,"US-TX":5.9,"US-UT":3.8,"US-VT":5.1,"US-VA":4.8,"US-WA":6.0,"US-WV":6.2,"US-WI":5.7,"US-WY":3.7},
 "2008":

<%= json_electoral_votes(@game) %>
,
 "2009":
 {"US-AL":13.1,"US-AK":9.5,"US-AZ":10.6,"US-AR":9.1,"US-CA":11.3,"US-CO":8.5,"US-CT":9.2,"US-DE":8.6,"US-DC":11.1,"US-FL":12.1,"US-GA":11.2,"US-HI":7.1,"US-ID":9.6,"US-IL":10.6,"US-IN":11.0,"US-IA":6.0,"US-KS":7.2,"US-KY":10.1,"US-LA":8.4,"US-ME":7.2,"US-MD":8.0,"US-MA":9.1,"US-MI":14.7,"US-MN":8.2,"US-MS":10.7,"US-MO":9.0,"US-MT":7.9,"US-NE":6.0,"US-NV":12.1,"US-NH":7.8,"US-NJ":9.8,"US-NM":9.0,"US-NY":9.0,"US-NC":11.0,"US-ND":3.8,"US-OH":11.1,"US-OK":6.8,"US-OR":11.8,"US-PA":9.1,"US-RI":9.6,"US-SC":11.7,"US-SD":5.2,"US-TN":11.1,"US-TX":8.2,"US-UT":7.8,"US-VT":7.6,"US-VA":7.4,"US-WA":9.5,"US-WV":7.7,"US-WI":8.2,"US-WY":5.9}
 }
 
}