config/routes.rb
Map::Application.routes.draw do

  resources :games do
    resources :player_states
    resources :voting_profiles

    post "roll"
    get "reset", :on => :member
    get "players"
  end

  resources :elections do
    member do 
      get :update_vote_table
    end
    resources :events
    resources :candidates
  end

  resources :events do
  end

  match 'event/outcome' => 'events#outcome', :via => :post
  match 'event/activate' => 'events#activate'

  match '/events/:event_id/:response' => 'events#outcome', :as=> :outcome, :via => :get

  get "maps/show"

root :to => 'games#new'

end

app/models/candidate.rb
# == Schema Information
#
# Table name: candidates
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#  party_id      :integer
#  image         :string(255)
#  election_id   :integer
#  campaign_date :date
#

class Candidate < ActiveRecord::Base

  attr_accessible :name, :party_id, :party, :image, :election, :campaign_date
  belongs_to :party
  belongs_to :election
  has_many :voting_profiles

  def electoral_votes
  	State.all.select { |s| s.winner==self}.collect { |s| s.electoral_votes }.sum
  end

  def profile_for(demo)
    demographic = demo.type_of.constantize.find(demo.value_id)
    voting_profiles.where("state_id = ?", demographic.id).first
  	#voting_profiles.each.select { |p| p.state_id == demographic.id }[0]
  end

  def votes
    voting_profiles.collect { |x| x.votes }.reduce(:+)
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
	def party_select
		collection_select(:candidate, :party_id, Party.all, :id, :name)
	end


end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %>
    <%= party_select %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Party</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.party.name %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Party:</b>
  <%= @candidate.party.name %>
</p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>